import '@/styles/globals.css';
import type { Metadata } from 'next';
import { openSans, roboto } from '@/lib/fonts';
import Footer from '@/components/common/Footer';
import Navbar from '@/components/common/Navbar';

export const metadata: Metadata = {
  title: {
    default: 'Job Finder: KodeBloc',
    template: '%s | KodeBloc Jobs',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${openSans.variable} font-sans antialiased`}
      >
        <div>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
